# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        folder:
          - adminSDK
          - advanced
          - ai
          - apps-script
          - calendar
          - chat
          - classroom
          - data-studio
          - docs
          - drive
          - forms
          - forms-api
          - gmail
          - gmail-sentiment-analysis
          - mashups
          - people
          - picker
          - service
          - sheets
          - slides
          - solutions
          - tasks
          - templates
          - triggers
          - ui
          - utils
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.head_ref || github.ref }}-${{ matrix.folder }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          cache: "pnpm"
      - run: pnpm i
      - run: pnpm check ${{ matrix.folder }}
